apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31333
    protocol: TCP
  selector:
    env: dev
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31256
    protocol: TCP
  selector:
    env: dev
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    env: dev
---
apiVersion: extensions/v1beta1
kind: deployment
metadata:
  name: my-deployment
spec:
  replicas: 10
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: x-container
        image: vijaykmm/docker-k8s:tagname
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container (- indicates list)
    image: vijaykmm/docker-k8s:tagname
    ports:
    - containerPort: 80
