apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: v1
kind: service
metadata:
 name: my-image
   image: vijaykmm/docker-k8s
   ports:
    - "443:80" 
