apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
  containers:
  - name: nginx
  image: vijaykmm/docker-k8s:tagname
  ports:
  - containerPort: 80
