apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
---
version: '3'
services:
 sample1:
   image: vijaykmm/docker-k8s
   ports:
    - "443:80" 
