apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: apache2
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31235
    protocol: TCP
  selector:
    app: apache2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: apache2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
      - name: nginx
        image: vijaykmm/docker-k8s
        ports:
        - containerPort: 80
